# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIngresodecodigo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ingresodecodigo(self):
    self.driver.get("https://inetvis.cinehoyts.cl/Compra/visSelectTickets.aspx?cinemacode=1091&txtSessionId=4334&distributor=&originalTitle=MINIONS+2%3a+NACE+UN+VILLANO&language=&genre=&rating=TE&director=Kyle+Balda&protagonist=undefined")
    self.driver.set_window_size(1387, 816)
    self.driver.find_element(By.ID, "txtVoucherEntry").click()
    self.driver.find_element(By.ID, "txtVoucherEntry").send_keys("890011968836")
    self.driver.find_element(By.ID, "ibtnAddToOrder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ErrorCell:nth-child(2)").click()
  
